andela-stuff/andela-teams-core

- README.md
- package.json
* Sets up the project using Yarn package manager
N/A
N/A
* There are certain advantages to using yarn over npm.
* Use yarn package manager #153892476
N/A
N/A
> #153892476 use yarn package manager

- .travis.yml
- package.json
* Integrates TravisCI with this Github repo
N/A
* Make a push to any branch of this repo to see Travis run
N/A
Integrate TravisCI with readme badge #153892572
N/A
N/A
> #153892572 integrate travis (2nd attempt)

- README.md
* Adds Travis CI badge to the README file
N/A
N/A
N/A
Integrate TravisCI with readme badge #153892572
N/A
N/A
> #153892572 add Travis CI badge to README

- .eslintrc.json
- package-lock.json
- package.json
- src/server.js
- yarn.lock
* sets up eslint for source code linting
N/A
N/A
N/A
Configure ESLint #153892539
N/A
N/A
> Ch config eslint 153892539

- .hound.yml
* integrates Hound CI with the project
N/A
N/A
N/A
Integrate HoundCI with badge attached to readme #153892530
N/A
N/A
> chore(houndci): integrate houndci

- README.md
* adds Hound CI badge to README
> chore: add Hound CI badge to README

- README.md
* adjusts Hound CI badge on README
> chore: adjust Hound CI badge on README

- .circleci/config.yml
- README.md
* Integrates Circle CI
* Integrate CircleCI #154095864
N/A
N/A
> #154095864 integrate circleci

- package.json
- src/server.js
- yarn.lock
* Gets the express app up in preparation for the tests
N/A
N/A
* Write tests for teams endpoints #153902285
N/A
N/A
> #153902285 write tests for teams endpoints (merge to staging)

- .eslintrc.json
- .gitignore
- package.json
- src/controllers/teams.js
- src/controllers/users.js
- src/routes/index.js
- src/server.js
- test/controllers/teams.spec.js
- test/controllers/users.spec.js
- yarn.lock
* Sets up passing tests for teams endpoints.
* Also sets up passing tests for users endpoints.
* Set up unit tests for various endpoints using `chai` and `chai-http`
* Run tests with Mocha
* Execute command `npm test`
N/A
Write tests for teams endpoints #153902285
N/A
> #153902285 Write tests for teams endpoints: set up passing tests for teams endpoints (take 3)

- .travis.yml
- package.json
- yarn.lock
> #153894006 Integrate Coveralls code coverage service (integrate codecov.io)

- src/routes/index.js
add sample @swagger comments
Implement API documentation #153902231
> #153902231 Implement API documentation

- .circleci/config.yml
- .travis.yml
- package.json
- src/configs/config.js
- src/controllers/teams.js
- src/controllers/users.js
- src/models/index.js
- yarn.lock
* Ensures Travis and Circle CI stop failing because of Postgres
Integrate Sequelize #154233349
> #154233349 Integrate Sequelize (fix Travis and Circle CI)

- src/config/config.js
- src/controllers/Auth.js
- src/middleware/Auth.js
- src/middleware/Validation.js
- src/middleware/index.js
- src/routes/teams.js
- src/routes/users.js
- test/controllers/auth.spec.js
- test/controllers/teams.spec.js
- test/controllers/users.spec.js
- test/mock/index.js
This PR adds `Auth` middleware which helps authenticate users.
Certain endpoints can be accessed only by authenticated users. This PR introduces a middleware that helps authenticate incoming requests.
Add auth middleware functionality #155342246
> #155342246 Add auth middleware functionality (take 3)

- package.json
- yarn.lock
Keeps the server awake on Heroku
Sometimes our server may go to sleep on Heroku. This may be due to it being idle for a while or an error that occurred during an attempted start-up.
`forever` will attempt to bring our server back up anytime it goes down. This is especially important when interacting with *impatient* services like Slack which are unwilling to wait for a sleeping server to come back up before terminating the request to the server.
[#155384235](https://www.pivotaltracker.com/story/show/155384235)
> #155384235 Use forever to keep the app awake on Heroku

- src/migrations/20180127130701-create-user.js
- src/migrations/20180127141250-create-team.js
- src/migrations/20180127141831-create-membership.js
- src/models/membership.js
- src/models/team.js
- src/models/user.js
Changes the data type of `id` column from `INTEGER` to `UUID`
It seems a better idea to use `UUID` than `INTEGER`. This PR changes the data type of the primary (and foreign) keys to `UUID`.
[#155481620](https://www.pivotaltracker.com/story/show/155481620)
> #155481620 Change data types of "id" to UUID

- package.json
- src/controllers/Auth.js
- src/controllers/Teams.js
- src/controllers/Users.js
- src/helpers/index.js
- src/middleware/Auth.js
- src/middleware/Validation.js
- src/migrations/20180127130701-create-user.js
- src/models/user.js
- test/controllers/auth.spec.js
- test/mock/index.js
Implements feature to allow users sign up with their Google account.
[#157336382](https://www.pivotaltracker.com/story/show/157336382)
> #157336382 Implement Google Authentication

- package.json
- src/migrations/20180127130701-create-user.js
- src/models/user.js
- the actual IDs returned from Google and Slack may be too large for INTEGER
- store them as STRING
[#157336382](https://www.pivotaltracker.com/story/show/157336382)
> feat(google-auth): change datatypes of google ID and slack ID

- package.json
- src/controllers/Users.js
- src/migrations/20180127130701-create-user.js
- src/models/user.js
- test/controllers/auth.spec.js
* adds `role` field to `User` schema
[#157452898](https://www.pivotaltracker.com/story/show/157452898)
> #157452898 add role to user

- package.json
- src/helpers/index.js
- src/middleware/Confirmation.js
- test/controllers/teams.spec.js
- test/mock/index.js
* redesigned the JSON returned from `teams` endpoints.
[#157452527](https://www.pivotaltracker.com/story/show/157452527)
> #157452527 new team schema

- test/controllers/teams.spec.js
- test/mock/index.js
* add tests for 'POST: /v1/teams'
tests should check for requirements like:
- it should not create a team with an existing name
- it should not create a team without a name
- it should not create a team by a user that is not an admin
[#157516506](https://www.pivotaltracker.com/story/show/157516506)
> #157516506 add tests for 'POST: /v1/teams'

- src/controllers/Teams.js
* rearrange the functions in the Teams controller
[#157516594](https://www.pivotaltracker.com/story/show/157516594)
> #157516594 rearrange the functions in Teams controller

- src/controllers/Teams.js
- src/middleware/Confirmation.js
- src/routes/teams.js
- test/controllers/teams.spec.js
* implements endpoint to get a single team
* add tests for the endpoint
[#157517041](https://www.pivotaltracker.com/story/show/157517041)
> #157517041 endpoint to get a single team

- src/controllers/Teams.js
- src/controllers/Users.js
- src/middleware/index.js
- src/middleware/sort.js
- src/routes/teams.js
- src/routes/users.js
- test/middleware/pagination.spec.js
- test/middleware/sort.spec.js
* adds middleware for sorting collections
* adds tests for sorts
[#155376979](https://www.pivotaltracker.com/story/show/155376979)
> #155376979 add middleware for sorting results

- src/controllers/Teams.js
- src/controllers/Users.js
- src/middleware/filter.js
- src/middleware/index.js
- src/routes/teams.js
- src/routes/users.js
- test/middleware/filter.spec.js
- test/middleware/sort.spec.js
* implement filtering of results in collections
* add tests for filters
[#155376979](https://www.pivotaltracker.com/story/show/155376979)
> #155376979 implement filter

- src/controllers/Teams.js
- src/controllers/Users.js
- src/helpers/index.js
- src/middleware/index.js
- src/middleware/search.js
- src/routes/teams.js
- src/routes/users.js
- test/middleware/search.spec.js
* implements the search of collections
* add tests for search
[#155376979](https://www.pivotaltracker.com/story/show/155376979)
> #155376979 implement search

- src/controllers/Members.js
- src/routes/members.js
- test/controllers/members.spec.js
* Adds endpoint to create memberships
* Adds endpoint to get a membership
* Add tests for the above implementations
[#157542502](https://www.pivotaltracker.com/story/show/157542502)
> #157542502 implement endpoints to add users to teams

- src/controllers/Members.js
- src/helpers/index.js
- src/routes/members.js
- test/controllers/members.spec.js
* Implements endpoint to get the memberships of a specified team
* Adds tests for the above implementation
[#157811433 Implement endpoint(s) to get memberships from a team](https://www.pivotaltracker.com/story/show/157811433)
> #157811433 implement endpoint to get memberships of a specified team

- package.json
- src/controllers/Accounts.js
- src/controllers/Auth.js
- src/controllers/Teams.js
- src/controllers/Users.js
- src/controllers/index.js
- src/helpers/index.js
- src/integrations/Slack.js
- src/middleware/Validate.js
- src/migrations/20180127130701-create-user.js
- src/migrations/20180527141831-create-account.js
- src/models/account.js
- src/models/team.js
- src/models/user.js
- src/routes/accounts.js
- src/routes/index.js
- src/routes/users.js
- test/controllers/users.spec.js
- yarn.lock
* Create endpoints for creating accounts
> #157542754 create accounts

- .babelrc
- .sequelizerc
- package.json
- src/server.js
- test/controllers/accounts.spec.js
- test/controllers/auth.spec.js
- test/controllers/members.spec.js
- test/controllers/teams.spec.js
- test/controllers/users.spec.js
- test/middleware/filter.spec.js
- test/middleware/pagination.spec.js
- test/middleware/search.spec.js
- test/middleware/sort.spec.js
- yarn.lock
Set up environments for  `testing`,`development`, and `production`
- Configure `Sequelize` for different environments
- Change the `build` process to suit different environments
- Fetch this branch with `git fetch ch-setup-app-environment-159221700:ch-setup-app-environment-159221700`
-  Checkout to the branch with `git checkout ch-setup-app-environment-159221700`
- Run `yarn/npm test` to run all the test
- Run `yarn/npm run start:dev` to start the application server
- Make changes to any of the files in the `src` folder and the changes should reflect when `nodemon` 
reloads the application.
- Change to different environments and test as much as you can.
N/A
[#159221700](https://www.pivotaltracker.com/n/projects/2138610/stories/159221700)
N/A
N/A
> #159221700 Setup application environment

- src/server.js
Set up environments for  `testing`,`development`, and `production`
- Configure `Sequelize` for different environments
- Change the `build` process to suit different environments
- Fetch this branch with `git fetch ch-setup-app-environment-159221700:ch-setup-app-environment-159221700`
-  Checkout to the branch with `git checkout ch-setup-app-environment-159221700`
- Run `yarn/npm test` to run all the test
- Run `yarn/npm run start:dev` to start the application server
- Make changes to any of the files in the `src` folder and the changes should reflect when `nodemon` 
reloads the application.
- Change to different environments and test as much as you can.
N/A
[#159221700](https://www.pivotaltracker.com/n/projects/2138610/stories/159221700)
N/A
N/A
> #159221700 Setup application environment 

- api.postman.json
- api.swagger20.json
- src/routes/auth.js
Creates Swagger API documentation for:
* `/v1/auth/signin`
* `/v1/auth/signup`
> write API documentation for authentication

- README.md
- api.postman.json
- api.swagger20.json
- src/controllers/Users.js
- src/routes/users.js
- src/server.js
- test/controllers/users.spec.js
Creates Swagger API documentation for:
* `/v1/users`
> write API documentation for Users controller

- src/controllers/Accounts.js
- src/integrations/Github.js
- src/integrations/PivotalTracker.js
- src/integrations/mock/index.js
- test/endpoints/teams.accounts.members.spec.js
Implements functionality to add a user to accounts of types `github_repo` and `github_private_repo`
[#157542778](https://www.pivotaltracker.com/story/show/157542778)
> #157542778 add user GitHub rep

- src/controllers/Accounts.js
- src/integrations/Slack.js
- src/integrations/mock/index.js
- test/endpoints/teams.accounts.members.spec.js
implements functionality to add a team member to the team account
[#157542778](https://www.pivotaltracker.com/story/show/157542778)
> #157542778 implement functionality to add user to Slack channel

- src/migrations/20181004193207-create-request.js
- src/models/request.js
- adds migration and model files for `request` object
[#159123743](https://www.pivotaltracker.com/story/show/159123743)
> #159123743 request schema 

- src/controllers/Requests.js
- src/controllers/index.js
- src/middleware/Validate.js
- src/routes/index.js
- src/routes/requests.js
- test/endpoints/requests.spec.js
- test/mock/index.js
Implements functionality to allow users to request to be admins.
[#160569090](https://www.pivotaltracker.com/story/show/160569090)
> #160569090 create request to be an admin

- src/controllers/Accounts.js
- src/helpers/index.js
- src/routes/teamAccounts.js
- test/endpoints/teams.accounts.spec.js
- Gets all accounts that a particular team has
- Added a method that gets all team account in the account controller
- Added an API route that gets all accounts of a team
- Clone this repo
- yarn install
- Add necessary env variable as specified in .env.sample
- yarn test
- This API enables a user to get the accounts of  a team
[#159219072](https://www.pivotaltracker.com/story/show/159219072)
> #159219072 Get accounts of a team

- src/controllers/Requests.js
- src/helpers/index.js
- src/routes/requests.js
- test/endpoints/requests.spec.js
Create an API endpoint that fetches all the requests
- fetch all the request in the database
- fetches requests based on the search, filter or sort
- Clone this repo
- yarn install
- Add necessary env variable as specified in .env.sample
- yarn test
[#160569126](https://www.pivotaltracker.com/story/show/160569126)
> #160569126 API endpoint to fetch all the request
